2021-03-09 12:27:22,146 INFO    MainThread:14520 [wandb_setup.py:_flush():69] setting env: {}
2021-03-09 12:27:22,146 INFO    MainThread:14520 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-09 12:27:22,146 INFO    MainThread:14520 [wandb_setup.py:_flush():69] setting login settings: {'api_key': '5bb01c6c68905943f7b41f69b0744c57000bf69c'}
2021-03-09 12:27:22,147 INFO    MainThread:14520 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210309_122722-3oc2wkpl\logs\debug.log
2021-03-09 12:27:22,147 INFO    MainThread:14520 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210309_122722-3oc2wkpl\logs\debug-internal.log
2021-03-09 12:27:22,150 INFO    MainThread:14520 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000219621C6A58>
2021-03-09 12:27:22,150 INFO    MainThread:14520 [wandb_init.py:init():367] calling init triggers
2021-03-09 12:27:22,151 INFO    MainThread:14520 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'n_layers': 3, 'hidden_layer_size': 64, 'learn_rate': 0.001, 'batch_size': 16, 'epochs': 10, 'alpha': 0.0005, 'optimizer': 'gradient_descent', 'activation': 'sigmoid', 'weight_init': 'random'}
2021-03-09 12:27:22,151 INFO    MainThread:14520 [wandb_init.py:init():416] starting backend
2021-03-09 12:27:22,151 INFO    MainThread:14520 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-09 12:27:22,164 INFO    MainThread:14520 [backend.py:ensure_launched():123] starting backend process...
2021-03-09 12:27:22,259 INFO    MainThread:14520 [backend.py:ensure_launched():128] started backend process with pid: 12376
2021-03-09 12:27:22,260 INFO    MainThread:14520 [wandb_init.py:init():421] backend started and connected
2021-03-09 12:27:22,272 INFO    MainThread:14520 [wandb_init.py:init():461] updated telemetry
2021-03-09 12:27:22,273 INFO    MainThread:14520 [wandb_init.py:init():480] communicating current version
2021-03-09 12:27:27,275 INFO    MainThread:14520 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-09 12:27:35,330 INFO    MainThread:14520 [wandb_init.py:init():518] starting run threads in backend
2021-03-09 12:27:39,830 INFO    MainThread:14520 [wandb_run.py:_console_start():1476] atexit reg
2021-03-09 12:27:39,833 INFO    MainThread:14520 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-09 12:27:39,836 INFO    MainThread:14520 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-09 12:27:39,837 INFO    MainThread:14520 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-09 12:27:39,837 INFO    MainThread:14520 [wandb_init.py:init():542] run started, returning control to user process
2021-03-09 12:27:39,839 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:39,839 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:46,459 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:46,930 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:46,930 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:46,951 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:47,570 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:47,570 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:47,592 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:47,594 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:47,594 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:47,613 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:47,616 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:47,616 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:47,915 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:47,917 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:47,917 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:48,477 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:48,844 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:48,845 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:48,968 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:48,971 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:48,972 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:49,402 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:49,405 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:49,406 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:49,639 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:49,641 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:49,641 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:50,101 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:50,103 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:50,103 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:50,593 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:50,596 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:50,597 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:51,267 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:51,270 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:51,270 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:51,957 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:51,976 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:51,976 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:52,616 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:52,638 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:52,639 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:53,218 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:53,253 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:53,254 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:53,857 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:53,861 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:53,861 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:55,339 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:55,345 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:55,345 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:56,140 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:56,150 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:56,151 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:27:58,547 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:27:58,551 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:27:58,551 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 12:28:08,279 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 12:30:57,320 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 12:30:57,321 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 13:13:41,810 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 13:15:56,629 ERROR   MainThread:14520 [util.py:get_module():189] Error importing optional module plotly.tools
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\util.py", line 184, in get_module
    return import_module(name)
  File "C:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1006, in _gcd_import
  File "<frozen importlib._bootstrap>", line 983, in _find_and_load
  File "<frozen importlib._bootstrap>", line 965, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'plotly'
2021-03-09 13:15:57,622 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 13:15:57,623 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 13:23:33,769 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 13:23:46,254 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 13:23:46,254 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 13:24:18,963 INFO    MainThread:14520 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-09 13:24:30,073 INFO    MainThread:14520 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-09 13:24:30,073 INFO    MainThread:14520 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-09 13:24:54,810 INFO    MainThread:14520 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-09 13:24:54,811 INFO    MainThread:14520 [wandb_run.py:_restore():1418] restore
2021-03-09 13:24:57,467 ERROR   MainThread:14520 [wandb_run.py:_atexit_cleanup():1464] Problem finishing run
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1454, in _atexit_cleanup
    self._on_finish()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 1590, in _on_finish
    self.history._flush()
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_history.py", line 59, in _flush
    self._callback(row=self._data, step=self._step)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\wandb_run.py", line 790, in _history_callback
    row, step, publish_step=not_using_tensorboard
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\interface\interface.py", line 211, in publish_history
    data = data_types.history_dict_to_json(run, data, step=step)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\data_types.py", line 1988, in history_dict_to_json
    payload[key] = val_to_json(run, key, val, namespace=step)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\data_types.py", line 2016, in val_to_json
    val = Plotly.make_plot_media(val)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\sdk\data_types.py", line 1938, in make_plot_media
    val = util.matplotlib_to_plotly(val)
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\util.py", line 412, in matplotlib_to_plotly
    required="plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`",
  File "C:\ProgramData\Anaconda3\lib\site-packages\wandb\util.py", line 191, in get_module
    raise wandb.Error(required)
wandb.errors.error.Error: plotly is required to log interactive plots, install with: pip install plotly or convert the plot to an image with `wandb.Image(plt)`
