2021-03-12 19:02:46,413 INFO    MainThread:912 [wandb_setup.py:_flush():69] setting env: {}
2021-03-12 19:02:46,414 INFO    MainThread:912 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-12 19:02:46,414 INFO    MainThread:912 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210312_190246-2p2qwra6\logs\debug.log
2021-03-12 19:02:46,414 INFO    MainThread:912 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210312_190246-2p2qwra6\logs\debug-internal.log
2021-03-12 19:02:46,414 INFO    MainThread:912 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000001B45DA23048>
2021-03-12 19:02:46,417 INFO    MainThread:912 [wandb_init.py:init():367] calling init triggers
2021-03-12 19:02:46,417 INFO    MainThread:912 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'n_layers': 4, 'hidden_layer_size': 128, 'learn_rate': 0.001, 'batch_size': 16, 'epochs': 10, 'alpha': 0, 'optimizer': 'nadam', 'activation': 'relu', 'weight_init': 'random'}
2021-03-12 19:02:46,417 INFO    MainThread:912 [wandb_init.py:init():416] starting backend
2021-03-12 19:02:46,417 INFO    MainThread:912 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-12 19:02:46,430 INFO    MainThread:912 [backend.py:ensure_launched():123] starting backend process...
2021-03-12 19:02:46,519 INFO    MainThread:912 [backend.py:ensure_launched():128] started backend process with pid: 4784
2021-03-12 19:02:46,520 INFO    MainThread:912 [wandb_init.py:init():421] backend started and connected
2021-03-12 19:02:46,532 INFO    MainThread:912 [wandb_init.py:init():461] updated telemetry
2021-03-12 19:02:46,534 INFO    MainThread:912 [wandb_init.py:init():480] communicating current version
2021-03-12 19:02:51,549 INFO    MainThread:912 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-12 19:02:59,333 INFO    MainThread:912 [wandb_init.py:init():518] starting run threads in backend
2021-03-12 19:03:02,278 INFO    MainThread:912 [wandb_run.py:_console_start():1476] atexit reg
2021-03-12 19:03:02,278 INFO    MainThread:912 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-12 19:03:02,279 INFO    MainThread:912 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-12 19:03:02,279 INFO    MainThread:912 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-12 19:03:02,279 INFO    MainThread:912 [wandb_init.py:init():542] run started, returning control to user process
2021-03-12 19:03:02,279 INFO    MainThread:912 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-12 19:03:02,280 INFO    MainThread:912 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-12 19:03:02,297 INFO    MainThread:912 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-12 19:03:02,741 INFO    MainThread:912 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-12 19:03:02,741 INFO    MainThread:912 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-12 19:03:08,359 INFO    MainThread:912 [wandb_init.py:_resume_backend():256] resuming backend
2021-03-12 19:03:08,804 INFO    MainThread:912 [wandb_init.py:_pause_backend():247] pausing backend
2021-03-12 19:03:08,804 INFO    MainThread:912 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-12 22:13:30,230 INFO    MainThread:912 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-12 22:13:30,231 INFO    MainThread:912 [wandb_run.py:_restore():1418] restore
2021-03-12 22:13:30,814 INFO    MainThread:912 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 23061
}

2021-03-12 22:13:32,832 INFO    MainThread:912 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 4
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 28774
}

2021-03-12 22:13:34,845 INFO    MainThread:912 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 4
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 28774
}

