2021-03-11 20:08:42,583 INFO    MainThread:6220 [wandb_setup.py:_flush():69] setting env: {}
2021-03-11 20:08:42,583 INFO    MainThread:6220 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-11 20:08:42,584 INFO    MainThread:6220 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210311_200842-2nxu8oq4\logs\debug.log
2021-03-11 20:08:42,584 INFO    MainThread:6220 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210311_200842-2nxu8oq4\logs\debug-internal.log
2021-03-11 20:08:42,585 INFO    MainThread:6220 [wandb_init.py:init():367] calling init triggers
2021-03-11 20:08:42,585 INFO    MainThread:6220 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'n_layers': 4, 'hidden_layer_size': 128, 'learn_rate': 0.001, 'batch_size': 16, 'epochs': 10, 'alpha': 0, 'optimizer': 'nadam', 'activation': 'relu', 'weight_init': 'random'}
2021-03-11 20:08:42,585 INFO    MainThread:6220 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 14os2nli
2021-03-11 20:08:42,587 INFO    MainThread:6220 [wandb_run.py:finish():1135] finishing run arneshbose1/deep_learning_assign2/14os2nli
2021-03-11 20:08:42,588 INFO    MainThread:6220 [jupyter.py:save_history():320] not saving jupyter history
2021-03-11 20:08:42,588 INFO    MainThread:6220 [jupyter.py:save_ipynb():265] not saving jupyter notebook
2021-03-11 20:08:42,588 INFO    MainThread:6220 [wandb_init.py:_jupyter_teardown():266] cleaning up jupyter logic
2021-03-11 20:08:42,588 INFO    MainThread:6220 [wandb_run.py:_atexit_cleanup():1446] got exitcode: 0
2021-03-11 20:08:42,588 INFO    MainThread:6220 [wandb_run.py:_restore():1418] restore
2021-03-11 20:08:43,040 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 1
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 23061
}

2021-03-11 20:08:45,047 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:47,056 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:49,057 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:51,073 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:53,075 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:55,084 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 23061
  total_bytes: 29078
}

2021-03-11 20:08:57,098 INFO    MainThread:6220 [wandb_run.py:_wait_for_finish():1568] got exit ret: done: true
exit_result {
}
file_counts {
  wandb_count: 5
  media_count: 1
}
pusher_stats {
  uploaded_bytes: 29078
  total_bytes: 29078
}

2021-03-11 20:08:58,328 INFO    MainThread:6220 [wandb_run.py:_show_summary():1723] rendering summary
2021-03-11 20:08:58,330 INFO    MainThread:6220 [wandb_run.py:_show_history():1761] rendering history
2021-03-11 20:08:58,331 INFO    MainThread:6220 [wandb_run.py:_show_files():1790] logging synced files
2021-03-11 20:08:58,338 INFO    MainThread:6220 [wandb_init.py:init():416] starting backend
2021-03-11 20:08:58,338 INFO    MainThread:6220 [backend.py:_multiprocessing_setup():71] multiprocessing start_methods=spawn, using: spawn
2021-03-11 20:08:58,342 INFO    MainThread:6220 [backend.py:ensure_launched():123] starting backend process...
2021-03-11 20:08:58,434 INFO    MainThread:6220 [backend.py:ensure_launched():128] started backend process with pid: 14868
2021-03-11 20:08:58,434 INFO    MainThread:6220 [wandb_init.py:init():421] backend started and connected
2021-03-11 20:08:58,445 INFO    MainThread:6220 [wandb_init.py:init():461] updated telemetry
2021-03-11 20:08:58,445 INFO    MainThread:6220 [wandb_init.py:init():480] communicating current version
2021-03-11 20:09:00,219 INFO    MainThread:6220 [wandb_init.py:init():485] got version response upgrade_message: "wandb version 0.10.22 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2021-03-11 20:09:00,220 INFO    MainThread:6220 [wandb_init.py:init():493] communicating run to backend with 30 second timeout
2021-03-11 20:09:00,756 INFO    MainThread:6220 [wandb_init.py:init():518] starting run threads in backend
2021-03-11 20:09:03,947 INFO    MainThread:6220 [wandb_run.py:_console_start():1476] atexit reg
2021-03-11 20:09:03,948 INFO    MainThread:6220 [wandb_run.py:_redirect():1339] redirect: SettingsConsole.WRAP
2021-03-11 20:09:03,948 INFO    MainThread:6220 [wandb_run.py:_redirect():1374] Wrapping output streams.
2021-03-11 20:09:03,948 INFO    MainThread:6220 [wandb_run.py:_redirect():1390] Redirects installed.
2021-03-11 20:09:03,948 INFO    MainThread:6220 [wandb_init.py:init():542] run started, returning control to user process
2021-03-11 20:59:19,653 INFO    MainThread:6220 [wandb_setup.py:_flush():69] setting env: {}
2021-03-11 20:59:19,653 INFO    MainThread:6220 [wandb_setup.py:_flush():69] setting login settings: {}
2021-03-11 20:59:19,653 INFO    MainThread:6220 [wandb_init.py:_log_setup():334] Logging user logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210311_205919-2kar27hb\logs\debug.log
2021-03-11 20:59:19,654 INFO    MainThread:6220 [wandb_init.py:_log_setup():335] Logging internal logs to C:\Users\Arnesh Kumar Bose\Desktop\CS6910 Assignments\wandb\run-20210311_205919-2kar27hb\logs\debug-internal.log
2021-03-11 20:59:19,654 INFO    MainThread:6220 [wandb_init.py:_jupyter_setup():285] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x00000203FFFC0710>
2021-03-11 20:59:19,655 INFO    MainThread:6220 [wandb_init.py:init():367] calling init triggers
2021-03-11 20:59:19,655 INFO    MainThread:6220 [wandb_init.py:init():374] wandb.init called with sweep_config: {}
config: {'n_layers': 4, 'hidden_layer_size': 128, 'learn_rate': 0.001, 'batch_size': 16, 'epochs': 10, 'alpha': 0, 'optimizer': 'nadam', 'activation': 'relu', 'weight_init': 'random'}
2021-03-11 20:59:19,655 INFO    MainThread:6220 [wandb_init.py:init():389] re-initializing run, found existing run on stack: 2nxu8oq4
2021-03-11 20:59:19,657 INFO    MainThread:6220 [wandb_run.py:finish():1135] finishing run arneshbose1/deep_learning_assign2/2nxu8oq4
